import UIProvider from '@/providers/UIProvider';

import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <UIProvider>
          <main className=" dark w-screen h-screen flex-box">{children}</main>
        </UIProvider>
      </body>
    </html>
  );
}
