import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';
import UIProvider from '@/providers/UIProvider';

import type { Metadata } from 'next';

import '../style/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="dark" suppressHydrationWarning>
      <body>
        <UIProvider>
          <Header />
          <main className=" w-screen h-screen flex-box">{children}</main>
          <Footer />
        </UIProvider>
      </body>
    </html>
  );
}
