name: Vercel Build Check

on:
  pull_request:
    branches: -dev

jobs:
  vercel-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.7.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # - name: Cache pnpm
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm-global
      #     key: ${{ runner.os }}-pnpm-cache
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-cache

      - name: Install dependencies (Production Only)
        run: pnpm install --frozen-lockfile

      - name: Set environment variables
        run: |
          echo "NEXT_PUBLIC_FB_API_KEY=${{ secrets.NEXT_PUBLIC_FB_API_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FB_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FB_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FB_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FB_PROJECT_ID }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FB_BUCKET=${{ secrets.NEXT_PUBLIC_FB_BUCKET }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FB_MESSAGING=${{ secrets.NEXT_PUBLIC_FB_MESSAGING }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FB_APP_ID=${{ secrets.NEXT_PUBLIC_FB_APP_ID }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FB_MEASUREMENT=${{ secrets.NEXT_PUBLIC_FB_MEASUREMENT }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_DICTIONARY_API_KEY=${{ secrets.NEXT_PUBLIC_DICTIONARY_API_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_GAME_CHAIN_SERVER=${{ secrets.NEXT_PUBLIC_GAME_CHAIN_SERVER }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: env | grep NEXT_PUBLIC_

      - name: Run tests
        run: pnpm run test

      - name: Check Test Success
        if: success()
        run: echo "✅ Test successful!"

      - name: Fail on Test Error
        if: failure()
        run: |
          echo "❌ Test failed!"
          exit 1

      - name: Run Next.js Build (without Vercel)
        run: pnpm run build

      - name: Check Build Success
        if: success()
        run: echo "✅ Build successful!"

      - name: Fail on Build Error
        if: failure()
        run: |
          echo "❌ Build failed!"
          exit 1
